example:
  property: "我是默认的网关配置"

zuul:
  # 配置 url 前缀
  prefix: '/api'
  # 配置需要忽略的服务 禁用所有服务
  ignored-services: '*'
  # 配置手动路由映射 只允许指定路由
  routes:
    organizationservice: '/organizationservice/**'
    licensingservice: '/licensingservice/**'
    organizationservicev2: '/organizationservicev2/**'

# 配置 actuator
management:
  endpoints:
    web:
      # 配置暴漏的服务
      exposure:
        include: '*'

# 配置 hystrix
hystrix:
  command:
    #配置所有服务
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 7000
    # 配置指定的服务
    licensingservice:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

# 配置指定服务的 ribbon 超时时间
licensingservice:
  ribbon:
    connectTimeout: 7000
    readTimeout: 7000