server:
  port: 7016


eureka:
  instance:
    # 注册服务的 IP 而不是名称
    prefer-ip-address: true
  client:
    # 注册自身到 eureka
    register-with-eureka: true
    # 在本地缓存注册表 每隔 30s 自动刷新服务
    fetch-registry: true
    service-url:
      # 配置注册中心地址
      defaultZone: http://localhost:7018/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'

# 设置日志级别
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.niu: DEBUG


spring:
  main:
    allow-bean-definition-overriding: true


# 配置oauth
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:7024/auth/users/me


