server:
  port: 7015

eureka:
  instance:
    # 注册服务的 IP 而不是名称
    prefer-ip-address: true
  client:
    # 注册自身到 eureka
    register-with-eureka: true
    # 在本地缓存注册表 每隔 30s 自动刷新服务
    fetch-registry: true
    service-url:
      # 配置注册中心地址
      defaultZone: http://localhost:7018/eureka/

# 配置日志输出等级
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.niu: DEBUG

# 配置 spring cloud stream
spring:
  cloud:
    stream:
      bindings:
        # 通道名称, 对于 source.output() 的通道
        output:
          # 推送的主题名称
          destination:  orgChangeTopic
          # 数据的类型
          content-type: application/json
        # 消息总线的类型
      kafka:
        binder:
          # 配置 zookeeper 的网络地址
          zkNodes: localhost:2181
          brokers: localhost:9092